baseURL = "https://jamisonkissh.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Jamison Kissh"
theme = "introduction"
# enableGitInfo = true
googleAnalytics = "UA-21890393-1"

[author]
  name = "Jamison Kissh"

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.

[params]
  themeStyle      = "auto"
  email = "hello@jamisonkissh.com"
      [params.home]
        introHeight              = "fullheight"
        localTime                = true
        timeZone                 = "America/New_York"
        timeFormat               = "en-US"
      [[params.social]]
        url   = "https://linkedin.com/in/jamisonkissh"
        icon  = "linkedin-in"
        icon_pack = "fab"
      [[params.social]]
        url = "mailto:hello@jamisonkissh.com"
        icon = "paper-plane"
        icon_pack = "fas"
      [[params.social]]
        url = "https://resume.jamisonkissh.com"
        icon = "user"
        icon_pack = "fas"
      [[params.social]]
        url = "https://blog.jamisonkissh.com"
        icon = "blog"
        icon_pack = "fas"
