baseURL = "https://jamisonkisshcom/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Jamison Kissh · Landing Page"

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Jamison Kissh"
  email = "hello@jamisonkissh.com"
  description = "Landing Page"
  bio = "Cloud Architecture Consultant. \nSecond Row."
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/jak119"
    instagram = "https://instagram.com/jak119"
    #twitter = "https://twitter.com/jdoe"
    #ello = ""
