name: Build and Deploy to Cloudflare

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_cloudflare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        if: github.actor != 'dependabot[bot]'
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: jamisonkissh-web
          directory: ./public/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}