name: Build and Deploy to Cloudflare

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_cloudflare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "16"
      - run: npm ci
      - name: Build
        run: hugo --minify
      # - name: Publish to Cloudflare
      #   uses: cloudflare/wrangler-action@2.0.0
      #   with:
      #     apiToken: ${{ secrets.CF_API_TOKEN }}
      #     accountId: ${{ secrets.CF_ACCOUNT_ID }}
      #     command: pages publish . --project-name=jamisonkissh-web
      #     workingDirectory: ./public/
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        if: github.actor != 'dependabot[bot]'
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: jamisonkissh-web
          directory: ./public/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}